'''exceptions.py
'''

class ValidationError(Exception):
    pass